### PR TITLE
Fix compile errors caused by unresolved headers

### PR DESCRIPTION
**Pull request by yuhe00**
I'm not sure what caused this problem for me, but I was not able to compile this plugin without making these changes (new, empty C++ project in launcher version of UE 4.21.2 , using VS 2017 14.16.27023).

### CODE REVIEW

**Comment by getnamo** [comment]
Are you placing the plugin in the engine folder or in your project folder? There is a new 4.22 version in the Engine which should support builds.

**Comment by yuhe00** [comment]
I am cloning the git repo to Plugins/LeapMotion in a new C++ project folder.

**Comment by getnamo** [comment]
Can you pull https://github.com/leapmotion/LeapUnreal/tree/fix-engine-headers to see if that compiles for you?

That branch merged header updates from the 3.0.1 engine merge which was updated by Epic. I'm trying to keep the header changes similar in both engine and project compiles.

**Comment by yuhe00** [comment]
Almost! Needed to add `#include "LeapUtility.h"` to `LeapWrapper.cpp` for missing log category.

**Comment by getnamo** [comment]
open a pull request with that change on that branch and ill merge it. Closing this one.

**Pull request closed without merging**
